using Wavee.Core.Catalog;

namespace Wavee.Backend.Catalog;

/// <summary>
/// One pure decision: after the extended-metadata BATCH arm has answered a key, must the dedicated single-key
/// endpoint (the "envelope" arm) still be asked?
///
/// <para>Only two facets have an envelope arm at all — <see cref="FacetKind.Availability"/> (one explicit
/// <c>getTrack</c> when TrackV4 omitted the file plane) and <see cref="FacetKind.UserIdentity"/>
/// (<c>/user-profile-view/v3/profile</c>). For every other facet the batch is authoritative and this returns
/// <see langword="false"/>.</para>
///
/// <para><b>Why this is a class and not an inline condition.</b> The condition it replaces treated ANY
/// <c>Present</c> batch answer as settling the key. For a user profile that is wrong, and wrong in a way the UI
/// shows to the user: Spotify's kind-15 USER_PROFILE payload for a modern autogenerated account often carries only
/// field 1 (the username) — no display name, no image. That decodes fine, so the batch reported
/// <c>Present</c> with <c>Name = null</c>, which suppressed the profile endpoint that WOULD have returned the
/// display name and avatar. The playlist header then rendered the bare id ("313ketyum7zs63mi7u3zgq3l4ily") with a
/// "3" initial for every collaborator, permanently — the cached facet is Present, so nothing ever refetched it.
/// <c>UserProfilePayload.IsRenderable</c> already existed for precisely this case and had unit tests; it was simply
/// never consulted in production. This is that check, moved to the place that can act on it.</para>
/// </summary>
static class BatchAnswerPolicy
{
    /// <summary>True when the envelope arm should run for this key despite the batch having answered.</summary>
    public static bool NeedsEnvelopeFallback(FacetKind facet, ResourceFetchResult result)
    {
        // No envelope endpoint exists for anything else — asking would be a wasted request per key.
        if (facet is not (FacetKind.Availability or FacetKind.UserIdentity)) return false;
        // Do not turn a transport problem, a 429 or a 403 into a second request: the envelope arm would hit the same
        // wall, and a per-key retry storm is how a rate limit becomes an outage.
        if (result.Error?.Kind is ResourceErrorKind.Transport or ResourceErrorKind.RateLimited or ResourceErrorKind.Forbidden)
            return false;
        // Unsupported means this key was never put on the wire (a document kind asked of the wrong entity kind).
        // That is a routing verdict about the KEY, not a gap in the answer, so the envelope arm cannot help either.
        if (result.Status == ResourceFetchStatus.Unsupported) return false;
        // A Present answer settles the key — UNLESS it is a user profile with nothing the owner row could draw.
        if (result.Status == ResourceFetchStatus.Present)
            return facet == FacetKind.UserIdentity && !CarriesRenderableProfile(result.Patch);
        // Absent, or a Failed the envelope arm may still answer (decode / invalid-response / persistence).
        return true;
    }

    /// <summary>Does this patch carry anything an owner row can show beyond the bare id? Mirrors
    /// <c>UserProfilePayload.IsRenderable</c>, one layer later: by here the payload has become a facet value.</summary>
    public static bool CarriesRenderableProfile(CatalogPatch? patch)
        => patch is ReplaceFacetPatch { Value: UserIdentityValue value }
           && (!string.IsNullOrWhiteSpace(value.Name) || !string.IsNullOrWhiteSpace(value.Avatar?.Url));
}
