//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -GenerateColorBindings -GenerateDependencyObject -Language CSharp -Namespace Wavee.UI.WinUI.Controls.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile LightRedEqualizer.json
//       
//       Input file:
//           LightRedEqualizer.json (11275 bytes created 0:44+02:00 Apr 10 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    47 |
// |--------------------------+-------|
// | Expression animators     |     8 |
// | KeyFrame animators       |     3 |
// | Reference parameters     |     8 |
// | Expression operations    |    16 |
// |--------------------------+-------|
// | Animated brushes         |     1 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     8 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace Wavee.UI.WinUI.Controls.AnimatedVisuals
{
    // Name:        Micro-Animation-Workshop:-Frame-1
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    public sealed class LightRedEqualizer
        : DependencyObject
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Theme property: Color_FF3F3F.
        internal static readonly Color c_themeColor_FF3F3F = Color.FromArgb(0xFF, 0xFF, 0x3F, 0x3F);

        CompositionPropertySet _themeProperties;

        /// <summary>
        /// Dependency property for Color_FF3F3F.
        /// </summary>
        public static readonly DependencyProperty Color_FF3F3FProperty =
            DependencyProperty.Register("Color_FF3F3F", typeof(Color), typeof(LightRedEqualizer),
                new PropertyMetadata(Color.FromArgb(0xFF, 0xFF, 0x3F, 0x3F), OnColor_FF3F3FChanged));

        // Theme properties.
        public Color Color_FF3F3F
        {
            get => (Color)GetValue(Color_FF3F3FProperty);
            set => SetValue(Color_FF3F3FProperty, value);
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        static void OnColor_FF3F3FChanged(DependencyObject d, DependencyPropertyChangedEventArgs args)
        {
            ((LightRedEqualizer)d)._themeProperties?.InsertVector4("Color_FF3F3F", ColorAsVector4((Color)(Color)args.NewValue));
        }

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Color_FF3F3F", ColorAsVector4((Color)Color_FF3F3F));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            var res = 
                new LightRedEqualizer_AnimatedVisual(
                    compositor,
                    _themeProperties
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 60d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(10000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 60d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Color_FF3F3F")
            {
                Color_FF3F3F = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class LightRedEqualizer_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            AnimationController _animationController_0;
            CompositionColorBrush _themeColor_Color_FF3F3F;
            CompositionRoundedRectangleGeometry _roundedRectangle_0;
            CompositionRoundedRectangleGeometry _roundedRectangle_1;
            CompositionRoundedRectangleGeometry _roundedRectangle_2;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // Color bound to theme property value: Color_FF3F3F
            CompositionColorBrush ThemeColor_Color_FF3F3F()
            {
                if (_themeColor_Color_FF3F3F != null) { return _themeColor_Color_FF3F3F; }
                var result = _themeColor_Color_FF3F3F = _c.CreateColorBrush();
                BindProperty(_themeColor_Color_FF3F3F, "Color", "ColorRGB(_theme.Color_FF3F3F.W,_theme.Color_FF3F3F.X,_theme.Color_FF3F3F.Y,_theme.Color_FF3F3F.Z)", "_theme", _themeProperties);
                return result;
            }

            // .RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_0()
            {
                if (_roundedRectangle_0 != null) { return _roundedRectangle_0; }
                var result = _roundedRectangle_0 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(0F, 0F);
                result.Offset = new Vector2(-8F, -8F);
                BindProperty(_roundedRectangle_0, "CornerRadius", "Vector2(Min(750,(Min(my.Size.X,my.Size.Y)/2)),Min(750,(Min(my.Size.X,my.Size.Y)/2)))", "my", _roundedRectangle_0);
                BindProperty(_roundedRectangle_0, "Offset", "Vector2(0,0)-(my.Size/Vector2(2,2))", "my", _roundedRectangle_0);
                return result;
            }

            // .RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_1()
            {
                if (_roundedRectangle_1 != null) { return _roundedRectangle_1; }
                var result = _roundedRectangle_1 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(0F, 0F);
                result.Offset = new Vector2(-8F, -8F);
                BindProperty(_roundedRectangle_1, "CornerRadius", "Vector2(Min(750,(Min(my.Size.X,my.Size.Y)/2)),Min(750,(Min(my.Size.X,my.Size.Y)/2)))", "my", _roundedRectangle_1);
                BindProperty(_roundedRectangle_1, "Offset", "Vector2(0,0)-(my.Size/Vector2(2,2))", "my", _roundedRectangle_1);
                return result;
            }

            // .RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_2()
            {
                if (_roundedRectangle_2 != null) { return _roundedRectangle_2; }
                var result = _roundedRectangle_2 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(0F, 0F);
                result.Offset = new Vector2(-8F, -8F);
                BindProperty(_roundedRectangle_2, "CornerRadius", "Vector2(Min(750,(Min(my.Size.X,my.Size.Y)/2)),Min(750,(Min(my.Size.X,my.Size.Y)/2)))", "my", _roundedRectangle_2);
                BindProperty(_roundedRectangle_2, "Offset", "Vector2(0,0)-(my.Size/Vector2(2,2))", "my", _roundedRectangle_2);
                return result;
            }

            // Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<30, 60>
                var geometry = RoundedRectangle_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 30F, 60F), ThemeColor_Color_FF3F3F());;
                return result;
            }

            // Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<60, 60>
                var geometry = RoundedRectangle_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 60F, 60F), ThemeColor_Color_FF3F3F());;
                return result;
            }

            // Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<90, 60>
                var geometry = RoundedRectangle_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 90F, 60F), ThemeColor_Color_FF3F3F());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(1F, 1F), new Vector2(0F, 0F))
                    : _cubicBezierEasingFunction_0;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(120F, 120F);
                var shapes = result.Shapes;
                // Offset:<30, 60>
                shapes.Add(SpriteShape_0());
                // Offset:<60, 60>
                shapes.Add(SpriteShape_1());
                // Offset:<90, 60>
                shapes.Add(SpriteShape_2());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // .RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(16F, 16F), HoldThenStepEasingFunction());
                // Frame 1.
                result.InsertKeyFrame(0.0166666675F, new Vector2(16F, 16.8099995F), CubicBezierEasingFunction_0());
                // Frame 2.
                result.InsertKeyFrame(0.0333333351F, new Vector2(16F, 18.4500008F), CubicBezierEasingFunction_0());
                // Frame 3.
                result.InsertKeyFrame(0.0500000007F, new Vector2(16F, 20.7399998F), CubicBezierEasingFunction_0());
                // Frame 4.
                result.InsertKeyFrame(0.0666666701F, new Vector2(16F, 23.1299992F), CubicBezierEasingFunction_0());
                // Frame 5.
                result.InsertKeyFrame(0.0833333358F, new Vector2(16F, 25.2299995F), CubicBezierEasingFunction_0());
                // Frame 6.
                result.InsertKeyFrame(0.100000001F, new Vector2(16F, 26.9400005F), CubicBezierEasingFunction_0());
                // Frame 7.
                result.InsertKeyFrame(0.116666667F, new Vector2(16F, 28.2900009F), CubicBezierEasingFunction_0());
                // Frame 8.
                result.InsertKeyFrame(0.13333334F, new Vector2(16F, 29.3500004F), CubicBezierEasingFunction_0());
                // Frame 9.
                result.InsertKeyFrame(0.150000006F, new Vector2(16F, 30.1800003F), CubicBezierEasingFunction_0());
                // Frame 10.
                result.InsertKeyFrame(0.166666672F, new Vector2(16F, 30.8099995F), CubicBezierEasingFunction_0());
                // Frame 11.
                result.InsertKeyFrame(0.183333337F, new Vector2(16F, 31.2800007F), CubicBezierEasingFunction_0());
                // Frame 12.
                result.InsertKeyFrame(0.200000003F, new Vector2(16F, 31.6200008F), CubicBezierEasingFunction_0());
                // Frame 13.
                result.InsertKeyFrame(0.216666669F, new Vector2(16F, 31.8400002F), CubicBezierEasingFunction_0());
                // Frame 14.
                result.InsertKeyFrame(0.233333334F, new Vector2(16F, 31.8400002F), CubicBezierEasingFunction_0());
                // Frame 15.
                result.InsertKeyFrame(0.25F, new Vector2(16F, 30.9599991F), CubicBezierEasingFunction_0());
                // Frame 16.
                result.InsertKeyFrame(0.266666681F, new Vector2(16F, 29.3600006F), CubicBezierEasingFunction_0());
                // Frame 17.
                result.InsertKeyFrame(0.283333331F, new Vector2(16F, 27.2199993F), CubicBezierEasingFunction_0());
                // Frame 18.
                result.InsertKeyFrame(0.300000012F, new Vector2(16F, 25F), CubicBezierEasingFunction_0());
                // Frame 19.
                result.InsertKeyFrame(0.316666663F, new Vector2(16F, 23.0200005F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.333333343F, new Vector2(16F, 21.3700008F), CubicBezierEasingFunction_0());
                // Frame 21.
                result.InsertKeyFrame(0.349999994F, new Vector2(16F, 20.0400009F), CubicBezierEasingFunction_0());
                // Frame 22.
                result.InsertKeyFrame(0.366666675F, new Vector2(16F, 18.9799995F), CubicBezierEasingFunction_0());
                // Frame 23.
                result.InsertKeyFrame(0.383333325F, new Vector2(16F, 18.1399994F), CubicBezierEasingFunction_0());
                // Frame 24.
                result.InsertKeyFrame(0.400000006F, new Vector2(16F, 17.4799995F), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.416666657F, new Vector2(16F, 16.9699993F), CubicBezierEasingFunction_0());
                // Frame 26.
                result.InsertKeyFrame(0.433333337F, new Vector2(16F, 16.5799999F), CubicBezierEasingFunction_0());
                // Frame 27.
                result.InsertKeyFrame(0.449999988F, new Vector2(16F, 16.3099995F), CubicBezierEasingFunction_0());
                // Frame 28.
                result.InsertKeyFrame(0.466666669F, new Vector2(16F, 16.1200008F), CubicBezierEasingFunction_0());
                // Frame 29.
                result.InsertKeyFrame(0.483333319F, new Vector2(16F, 16.0300007F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.5F, new Vector2(16F, 16.2000008F), CubicBezierEasingFunction_0());
                // Frame 31.
                result.InsertKeyFrame(0.516666651F, new Vector2(16F, 19.3700008F), CubicBezierEasingFunction_0());
                // Frame 32.
                result.InsertKeyFrame(0.533333361F, new Vector2(16F, 25.5F), CubicBezierEasingFunction_0());
                // Frame 33.
                result.InsertKeyFrame(0.550000012F, new Vector2(16F, 33.7200012F), CubicBezierEasingFunction_0());
                // Frame 34.
                result.InsertKeyFrame(0.566666663F, new Vector2(16F, 42.0499992F), CubicBezierEasingFunction_0());
                // Frame 35.
                result.InsertKeyFrame(0.583333313F, new Vector2(16F, 49.2299995F), CubicBezierEasingFunction_0());
                // Frame 36.
                result.InsertKeyFrame(0.600000024F, new Vector2(16F, 55.0400009F), CubicBezierEasingFunction_0());
                // Frame 37.
                result.InsertKeyFrame(0.616666675F, new Vector2(16F, 59.6300011F), CubicBezierEasingFunction_0());
                // Frame 38.
                result.InsertKeyFrame(0.633333325F, new Vector2(16F, 63.2200012F), CubicBezierEasingFunction_0());
                // Frame 39.
                result.InsertKeyFrame(0.649999976F, new Vector2(16F, 66.0100021F), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, new Vector2(16F, 68.1299973F), CubicBezierEasingFunction_0());
                // Frame 41.
                result.InsertKeyFrame(0.683333337F, new Vector2(16F, 69.6999969F), CubicBezierEasingFunction_0());
                // Frame 42.
                result.InsertKeyFrame(0.699999988F, new Vector2(16F, 70.8199997F), CubicBezierEasingFunction_0());
                // Frame 43.
                result.InsertKeyFrame(0.716666639F, new Vector2(16F, 71.5299988F), CubicBezierEasingFunction_0());
                // Frame 44.
                result.InsertKeyFrame(0.733333349F, new Vector2(16F, 71.9100037F), CubicBezierEasingFunction_0());
                // Frame 45.
                result.InsertKeyFrame(0.75F, new Vector2(16F, 71.6299973F), CubicBezierEasingFunction_0());
                // Frame 46.
                result.InsertKeyFrame(0.766666651F, new Vector2(16F, 68.1999969F), CubicBezierEasingFunction_0());
                // Frame 47.
                result.InsertKeyFrame(0.783333361F, new Vector2(16F, 61.8199997F), CubicBezierEasingFunction_0());
                // Frame 48.
                result.InsertKeyFrame(0.800000012F, new Vector2(16F, 53.5099983F), CubicBezierEasingFunction_0());
                // Frame 49.
                result.InsertKeyFrame(0.816666663F, new Vector2(16F, 45.25F), CubicBezierEasingFunction_0());
                // Frame 50.
                result.InsertKeyFrame(0.833333313F, new Vector2(16F, 38.1899986F), CubicBezierEasingFunction_0());
                // Frame 51.
                result.InsertKeyFrame(0.850000024F, new Vector2(16F, 32.5F), CubicBezierEasingFunction_0());
                // Frame 52.
                result.InsertKeyFrame(0.866666675F, new Vector2(16F, 28.0100002F), CubicBezierEasingFunction_0());
                // Frame 53.
                result.InsertKeyFrame(0.883333325F, new Vector2(16F, 24.5F), CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.899999976F, new Vector2(16F, 21.7800007F), CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.916666687F, new Vector2(16F, 19.7099991F), CubicBezierEasingFunction_0());
                // Frame 56.
                result.InsertKeyFrame(0.933333337F, new Vector2(16F, 18.1800003F), CubicBezierEasingFunction_0());
                // Frame 57.
                result.InsertKeyFrame(0.949999988F, new Vector2(16F, 17.1000004F), CubicBezierEasingFunction_0());
                // Frame 58.
                result.InsertKeyFrame(0.966666639F, new Vector2(16F, 16.4200001F), CubicBezierEasingFunction_0());
                // Frame 59.
                result.InsertKeyFrame(0.983333349F, new Vector2(16F, 16.0699997F), CubicBezierEasingFunction_0());
                return result;
            }

            // .RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(16F, 16F), HoldThenStepEasingFunction());
                // Frame 1.
                result.InsertKeyFrame(0.0166666675F, new Vector2(16F, 18.8199997F), CubicBezierEasingFunction_0());
                // Frame 2.
                result.InsertKeyFrame(0.0333333351F, new Vector2(16F, 24.5599995F), CubicBezierEasingFunction_0());
                // Frame 3.
                result.InsertKeyFrame(0.0500000007F, new Vector2(16F, 32.5800018F), CubicBezierEasingFunction_0());
                // Frame 4.
                result.InsertKeyFrame(0.0666666701F, new Vector2(16F, 40.9700012F), CubicBezierEasingFunction_0());
                // Frame 5.
                result.InsertKeyFrame(0.0833333358F, new Vector2(16F, 48.3100014F), CubicBezierEasingFunction_0());
                // Frame 6.
                result.InsertKeyFrame(0.100000001F, new Vector2(16F, 54.2900009F), CubicBezierEasingFunction_0());
                // Frame 7.
                result.InsertKeyFrame(0.116666667F, new Vector2(16F, 59.0200005F), CubicBezierEasingFunction_0());
                // Frame 8.
                result.InsertKeyFrame(0.13333334F, new Vector2(16F, 62.7299995F), CubicBezierEasingFunction_0());
                // Frame 9.
                result.InsertKeyFrame(0.150000006F, new Vector2(16F, 65.6200027F), CubicBezierEasingFunction_0());
                // Frame 10.
                result.InsertKeyFrame(0.166666672F, new Vector2(16F, 67.8300018F), CubicBezierEasingFunction_0());
                // Frame 11.
                result.InsertKeyFrame(0.183333337F, new Vector2(16F, 69.4800034F), CubicBezierEasingFunction_0());
                // Frame 12.
                result.InsertKeyFrame(0.200000003F, new Vector2(16F, 70.6600037F), CubicBezierEasingFunction_0());
                // Frame 13.
                result.InsertKeyFrame(0.216666669F, new Vector2(16F, 71.4400024F), CubicBezierEasingFunction_0());
                // Frame 14.
                result.InsertKeyFrame(0.233333334F, new Vector2(16F, 71.8700027F), CubicBezierEasingFunction_0());
                // Frame 15.
                result.InsertKeyFrame(0.25F, new Vector2(16F, 70.3799973F), CubicBezierEasingFunction_0());
                // Frame 16.
                result.InsertKeyFrame(0.266666681F, new Vector2(16F, 66.8600006F), CubicBezierEasingFunction_0());
                // Frame 17.
                result.InsertKeyFrame(0.283333331F, new Vector2(16F, 61.6699982F), CubicBezierEasingFunction_0());
                // Frame 18.
                result.InsertKeyFrame(0.300000012F, new Vector2(16F, 55.9099998F), CubicBezierEasingFunction_0());
                // Frame 19.
                result.InsertKeyFrame(0.316666663F, new Vector2(16F, 50.6199989F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.333333343F, new Vector2(16F, 46.2099991F), CubicBezierEasingFunction_0());
                // Frame 21.
                result.InsertKeyFrame(0.349999994F, new Vector2(16F, 42.6599998F), CubicBezierEasingFunction_0());
                // Frame 22.
                result.InsertKeyFrame(0.366666675F, new Vector2(16F, 39.8199997F), CubicBezierEasingFunction_0());
                // Frame 23.
                result.InsertKeyFrame(0.383333325F, new Vector2(16F, 37.5900002F), CubicBezierEasingFunction_0());
                // Frame 24.
                result.InsertKeyFrame(0.400000006F, new Vector2(16F, 35.8400002F), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.416666657F, new Vector2(16F, 34.4900017F), CubicBezierEasingFunction_0());
                // Frame 26.
                result.InsertKeyFrame(0.433333337F, new Vector2(16F, 33.4900017F), CubicBezierEasingFunction_0());
                // Frame 27.
                result.InsertKeyFrame(0.449999988F, new Vector2(16F, 32.7700005F), CubicBezierEasingFunction_0());
                // Frame 28.
                result.InsertKeyFrame(0.466666669F, new Vector2(16F, 32.3100014F), CubicBezierEasingFunction_0());
                // Frame 29.
                result.InsertKeyFrame(0.483333319F, new Vector2(16F, 32.0600014F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.5F, new Vector2(16F, 31.9400005F), CubicBezierEasingFunction_0());
                // Frame 31.
                result.InsertKeyFrame(0.516666651F, new Vector2(16F, 31.0400009F), CubicBezierEasingFunction_0());
                // Frame 32.
                result.InsertKeyFrame(0.533333361F, new Vector2(16F, 29.2900009F), CubicBezierEasingFunction_0());
                // Frame 33.
                result.InsertKeyFrame(0.550000012F, new Vector2(16F, 26.9400005F), CubicBezierEasingFunction_0());
                // Frame 34.
                result.InsertKeyFrame(0.566666663F, new Vector2(16F, 24.5599995F), CubicBezierEasingFunction_0());
                // Frame 35.
                result.InsertKeyFrame(0.583333313F, new Vector2(16F, 22.5F), CubicBezierEasingFunction_0());
                // Frame 36.
                result.InsertKeyFrame(0.600000024F, new Vector2(16F, 20.8500004F), CubicBezierEasingFunction_0());
                // Frame 37.
                result.InsertKeyFrame(0.616666675F, new Vector2(16F, 19.5300007F), CubicBezierEasingFunction_0());
                // Frame 38.
                result.InsertKeyFrame(0.633333325F, new Vector2(16F, 18.5100002F), CubicBezierEasingFunction_0());
                // Frame 39.
                result.InsertKeyFrame(0.649999976F, new Vector2(16F, 17.7099991F), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, new Vector2(16F, 17.1100006F), CubicBezierEasingFunction_0());
                // Frame 41.
                result.InsertKeyFrame(0.683333337F, new Vector2(16F, 16.6599998F), CubicBezierEasingFunction_0());
                // Frame 42.
                result.InsertKeyFrame(0.699999988F, new Vector2(16F, 16.3400002F), CubicBezierEasingFunction_0());
                // Frame 43.
                result.InsertKeyFrame(0.716666639F, new Vector2(16F, 16.1299992F), CubicBezierEasingFunction_0());
                // Frame 44.
                result.InsertKeyFrame(0.733333349F, new Vector2(16F, 16.0200005F), CubicBezierEasingFunction_0());
                // Frame 45.
                result.InsertKeyFrame(0.75F, new Vector2(16F, 16F), CubicBezierEasingFunction_0());
                return result;
            }

            // .RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(16F, 16F), HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.233333334F, new Vector2(16F, 16F), CubicBezierEasingFunction_0());
                // Frame 15.
                result.InsertKeyFrame(0.25F, new Vector2(16F, 18.1299992F), CubicBezierEasingFunction_0());
                // Frame 16.
                result.InsertKeyFrame(0.266666681F, new Vector2(16F, 23.0699997F), CubicBezierEasingFunction_0());
                // Frame 17.
                result.InsertKeyFrame(0.283333331F, new Vector2(16F, 30.3500004F), CubicBezierEasingFunction_0());
                // Frame 18.
                result.InsertKeyFrame(0.300000012F, new Vector2(16F, 38.4500008F), CubicBezierEasingFunction_0());
                // Frame 19.
                result.InsertKeyFrame(0.316666663F, new Vector2(16F, 45.8699989F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(0.333333343F, new Vector2(16F, 52.0499992F), CubicBezierEasingFunction_0());
                // Frame 21.
                result.InsertKeyFrame(0.349999994F, new Vector2(16F, 57.0499992F), CubicBezierEasingFunction_0());
                // Frame 22.
                result.InsertKeyFrame(0.366666675F, new Vector2(16F, 61.0200005F), CubicBezierEasingFunction_0());
                // Frame 23.
                result.InsertKeyFrame(0.383333325F, new Vector2(16F, 64.1600037F), CubicBezierEasingFunction_0());
                // Frame 24.
                result.InsertKeyFrame(0.400000006F, new Vector2(16F, 66.6100006F), CubicBezierEasingFunction_0());
                // Frame 25.
                result.InsertKeyFrame(0.416666657F, new Vector2(16F, 68.5F), CubicBezierEasingFunction_0());
                // Frame 26.
                result.InsertKeyFrame(0.433333337F, new Vector2(16F, 69.9100037F), CubicBezierEasingFunction_0());
                // Frame 27.
                result.InsertKeyFrame(0.449999988F, new Vector2(16F, 70.9100037F), CubicBezierEasingFunction_0());
                // Frame 28.
                result.InsertKeyFrame(0.466666669F, new Vector2(16F, 71.5699997F), CubicBezierEasingFunction_0());
                // Frame 29.
                result.InsertKeyFrame(0.483333319F, new Vector2(16F, 71.9199982F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.5F, new Vector2(16F, 71.8600006F), CubicBezierEasingFunction_0());
                // Frame 31.
                result.InsertKeyFrame(0.516666651F, new Vector2(16F, 69.5899963F), CubicBezierEasingFunction_0());
                // Frame 32.
                result.InsertKeyFrame(0.533333361F, new Vector2(16F, 65.2099991F), CubicBezierEasingFunction_0());
                // Frame 33.
                result.InsertKeyFrame(0.550000012F, new Vector2(16F, 59.3499985F), CubicBezierEasingFunction_0());
                // Frame 34.
                result.InsertKeyFrame(0.566666663F, new Vector2(16F, 53.3899994F), CubicBezierEasingFunction_0());
                // Frame 35.
                result.InsertKeyFrame(0.583333313F, new Vector2(16F, 48.2599983F), CubicBezierEasingFunction_0());
                // Frame 36.
                result.InsertKeyFrame(0.600000024F, new Vector2(16F, 44.1100006F), CubicBezierEasingFunction_0());
                // Frame 37.
                result.InsertKeyFrame(0.616666675F, new Vector2(16F, 40.8400002F), CubicBezierEasingFunction_0());
                // Frame 38.
                result.InsertKeyFrame(0.633333325F, new Vector2(16F, 38.2700005F), CubicBezierEasingFunction_0());
                // Frame 39.
                result.InsertKeyFrame(0.649999976F, new Vector2(16F, 36.2799988F), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, new Vector2(16F, 34.7700005F), CubicBezierEasingFunction_0());
                // Frame 41.
                result.InsertKeyFrame(0.683333337F, new Vector2(16F, 33.6399994F), CubicBezierEasingFunction_0());
                // Frame 42.
                result.InsertKeyFrame(0.699999988F, new Vector2(16F, 32.8499985F), CubicBezierEasingFunction_0());
                // Frame 43.
                result.InsertKeyFrame(0.716666639F, new Vector2(16F, 32.3300018F), CubicBezierEasingFunction_0());
                // Frame 44.
                result.InsertKeyFrame(0.733333349F, new Vector2(16F, 32.0600014F), CubicBezierEasingFunction_0());
                // Frame 45.
                result.InsertKeyFrame(0.75F, new Vector2(16F, 31.8899994F), CubicBezierEasingFunction_0());
                // Frame 46.
                result.InsertKeyFrame(0.766666651F, new Vector2(16F, 30.9099998F), CubicBezierEasingFunction_0());
                // Frame 47.
                result.InsertKeyFrame(0.783333361F, new Vector2(16F, 29.0900002F), CubicBezierEasingFunction_0());
                // Frame 48.
                result.InsertKeyFrame(0.800000012F, new Vector2(16F, 26.7199993F), CubicBezierEasingFunction_0());
                // Frame 49.
                result.InsertKeyFrame(0.816666663F, new Vector2(16F, 24.3600006F), CubicBezierEasingFunction_0());
                // Frame 50.
                result.InsertKeyFrame(0.833333313F, new Vector2(16F, 22.3400002F), CubicBezierEasingFunction_0());
                // Frame 51.
                result.InsertKeyFrame(0.850000024F, new Vector2(16F, 20.7099991F), CubicBezierEasingFunction_0());
                // Frame 52.
                result.InsertKeyFrame(0.866666675F, new Vector2(16F, 19.4300003F), CubicBezierEasingFunction_0());
                // Frame 53.
                result.InsertKeyFrame(0.883333325F, new Vector2(16F, 18.4300003F), CubicBezierEasingFunction_0());
                // Frame 54.
                result.InsertKeyFrame(0.899999976F, new Vector2(16F, 17.6499996F), CubicBezierEasingFunction_0());
                // Frame 55.
                result.InsertKeyFrame(0.916666687F, new Vector2(16F, 17.0599995F), CubicBezierEasingFunction_0());
                // Frame 56.
                result.InsertKeyFrame(0.933333337F, new Vector2(16F, 16.6200008F), CubicBezierEasingFunction_0());
                // Frame 57.
                result.InsertKeyFrame(0.949999988F, new Vector2(16F, 16.3199997F), CubicBezierEasingFunction_0());
                // Frame 58.
                result.InsertKeyFrame(0.966666639F, new Vector2(16F, 16.1200008F), CubicBezierEasingFunction_0());
                // Frame 59.
                result.InsertKeyFrame(0.983333349F, new Vector2(16F, 16.0200005F), CubicBezierEasingFunction_0());
                return result;
            }

            internal LightRedEqualizer_AnimatedVisual(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(120F, 120F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _roundedRectangle_0.StartAnimation("Size", SizeVector2Animation_0(), AnimationController_0());
                _roundedRectangle_1.StartAnimation("Size", SizeVector2Animation_1(), AnimationController_0());
                _roundedRectangle_2.StartAnimation("Size", SizeVector2Animation_2(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _roundedRectangle_0.StopAnimation("Size");
                _roundedRectangle_1.StopAnimation("Size");
                _roundedRectangle_2.StopAnimation("Size");
            }

        }
    }
}
