using System.Net.Http.Headers;
using System.Text;
using Google.Protobuf;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Serilog;
using Serilog.Events;
using Spectre.Console;
using Wavee.Console;
using Wavee.Core.Authentication;
using Wavee.Core.Session;
using Wavee.OAuth;
using Wavee.Protocol.DescriptorExtension;
using Wavee.Protocol.ExtendedMetadata;
using Wavee.Protocol.Metadata;

// Enable UTF-8 output for Korean/Unicode characters
Console.OutputEncoding = Encoding.UTF8;
Console.InputEncoding = Encoding.UTF8;

var request = new BatchedEntityRequest
{
    Header = new BatchedEntityRequestHeader
    {
        Country = "KR",
        Catalogue = "premium"
    }
};
//https://open.spotify.com/track/4EWBhKf1fOFnyMtUzACXEc?si=3cd0266ec1b048e5
request.EntityRequest.Add(new EntityRequest
{
    EntityUri = "spotify:track:4EWBhKf1fOFnyMtUzACXEc",
    Query =
    {
        new ExtensionQuery
        {
            ExtensionKind = ExtensionKind.TrackDescriptor
        }
    }
});
//Ch8KAk5MEgdwcmVtaXVtGhBqrCiHbAl1CmsMusvHAnw1EioKJHNwb3RpZnk6dHJhY2s6NFpoSjVOOEVyNENmcGFOYWtVUVRrUBICCAYSKgokc3BvdGlmeTp0cmFjazo0Wm5reWdvV0x6Y0diUVlDbTNsa2FlEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRhN1ZnWXZLbWo0UTlkYzN2UnVvREMSAggGEioKJHNwb3RpZnk6dHJhY2s6NGFKelBNekVUYTJrU20xR3o4UGxCeBICCAYSKgokc3BvdGlmeTp0cmFjazo0YjMwcnhlNGt4ak5sOFlwRTE3U2V3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRiNTBYYkhramhGNzNqNnZKYXBSSkYSAggGEioKJHNwb3RpZnk6dHJhY2s6NGNlV21LUlBlM1BHWHo0WnlFdDNsZRICCAYSKgokc3BvdGlmeTp0cmFjazo0ZUZUaDFvcExTNXdBTkRtWks5Z2hDEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRld2F6UUxYRlREQzhYdkNiaHZ0WHMSAggGEioKJHNwb3RpZnk6dHJhY2s6NGV5Qml3c2FHQlJDakFDR1pLWnNmNxICCAYSKgokc3BvdGlmeTp0cmFjazo0ZmozSTZVT2IzN3JPdHRqSmFja2RqEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRnTVBsSEhBak9RblVyaHN1cUhpdm4SAggGEioKJHNwb3RpZnk6dHJhY2s6NGhwR0hvSnVKVHRBcXE5cGtldkxwNhICCAYSKgokc3BvdGlmeTp0cmFjazo0aUpaMTJndmN1bmY4MGd5bTdxRU0yEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRpbmNrVklmT1hYN2VpSVNDMDFVeFoSAggGEioKJHNwb3RpZnk6dHJhY2s6NGl0ZE92ZzZWOGhqVE9RVWVhR0hXdBICCAYSKgokc3BvdGlmeTp0cmFjazo0a3ZLWTQzd0J6UWFoeFNhdlBZVUl2EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRsNWU0RzFSenJmV1dGZ2Vob0VnQUgSAggGEioKJHNwb3RpZnk6dHJhY2s6NG00YVFMaVBiV0Z5RTA3eFJvSlBoYxICCAYSKgokc3BvdGlmeTp0cmFjazo0bXFmZTlYcmdFT1Nzb2Z2cTVNeWpSEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRuZHhDcnRsNzRsZ09kRjZMejdiSXESAggGEioKJHNwb3RpZnk6dHJhY2s6NG56QlNUOUpkWkl5OXFmaWxyOTNQbxICCAYSKgokc3BvdGlmeTp0cmFjazo0b0hROG45T0tRMzU5OWU4bm9DckRYEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRxM2JpYVFRb0FEc3BWMTZsYnNmUEgSAggGEioKJHNwb3RpZnk6dHJhY2s6NHFOSzl6YlJmbzAzU0dqYXNtTHlhRxICCAYSKgokc3BvdGlmeTp0cmFjazo0cWRlNDFLTmZKdjJUeXJLQzFrdWc3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRxd3R4cGhRUzJHZlBpRGI2TUpKa0sSAggGEioKJHNwb3RpZnk6dHJhY2s6NHNUalVZaklDMDJSa05hMUE4cldqRRICCAYSKgokc3BvdGlmeTp0cmFjazo0dDVqb1prZGxYbHZ6TFhKYmtncHBKEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjR3SjVRcTBqQk40YWp5N291WklWMWMSAggGEioKJHNwb3RpZnk6dHJhY2s6NHhldWdCNU1xV2gwand2WFpQeGFocRICCAYSKgokc3BvdGlmeTp0cmFjazo0eHB4MEJsZmFUZDY0eWNpRldsTTR3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjR5Tms5aXo5V1ZKaWtSRmxlM1hFdm4SAggGEioKJHNwb3RpZnk6dHJhY2s6NHlzb3dLN2hKZ0kxUVI0dFA1QUQ0dBICCAYSKgokc3BvdGlmeTp0cmFjazo0eXR5THBJd1VYYmRGc05PdmdObm1QEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjUyVGR1dU9FNHJWbmhMREFHQjRRUEUSAggGEioKJHNwb3RpZnk6dHJhY2s6NTJwNVJ0RWFUWHgxdTF1ZHJ4OEZxchICCAYSKgokc3BvdGlmeTp0cmFjazo1MnR1bXdFZENBcDdUckoxUUxOQWhvEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjUzVDVtWnVxQWp2bTBwaW5VZndJWHISAggGEioKJHNwb3RpZnk6dHJhY2s6NTVvY0pQUnhXdWVnbzRwa0ZQVVpDYhICCAYSKgokc3BvdGlmeTp0cmFjazo1N2RxUVE3Nzl5Y1FEUE9jZzNkNWRVEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjU4NGhUT08yMEIyV0tLOFBqUEIxR3cSAggGEioKJHNwb3RpZnk6dHJhY2s6NUVoMW5qN0lqVjlsd3BjS0FraWR5WRICCAYSKgokc3BvdGlmeTp0cmFjazo1RWp2bHlqTXdxbWFiWGdGREQ4RDJ4EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVGS2RXVDVBN3ZEVEVuUGlIcnJ1RlkSAggGEioKJHNwb3RpZnk6dHJhY2s6NUZWYnZ0dGpFdlE4cjJCZ1VjSmdOZxICCAYSKgokc3BvdGlmeTp0cmFjazo1R0dFZE5FdHpvNktMVFZSTFdrZFdhEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVKcGZjdWZyME1lQmVvWmRvS0s4dXkSAggGEioKJHNwb3RpZnk6dHJhY2s6NUpwZnRVSGVVengzeldFNnJadGtpNRICCAYSKgokc3BvdGlmeTp0cmFjazo1S2JwY2QzaE9xdTRaUkFKTkFqSWNnEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVMOG1SZ1I3RXl3Zk1icENBdWRkTlMSAggGEioKJHNwb3RpZnk6dHJhY2s6NUxFTXNKOERBc0NxWU9sbUpjaUZTWRICCAYSKgokc3BvdGlmeTp0cmFjazo1THZGYUtzMVFOMm5SNjVoNHRKTjRSEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVNR1pQbjdRV0dEM0RUbVB5cnBqNzkSAggGEioKJHNwb3RpZnk6dHJhY2s6NVBkMUszMXlnTEpqZ2JwQUU2aWNyNBICCAYSKgokc3BvdGlmeTp0cmFjazo1UktuSEwwcGNUNWZQTkIzOG9MNHd2EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVTaDJwSlQzVldUdmtRT1hQQWFSaUMSAggGEioKJHNwb3RpZnk6dHJhY2s6NVRlRElRcnB3V3RMV2FGZnpMSDBoaBICCAYSKgokc3BvdGlmeTp0cmFjazo1VHV6UTQ0bFBXVENLYmZYYk5JRVhnEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVVZUl3Y1VJS1RWUHFCbnVYbmhtQkQSAggGEioKJHNwb3RpZnk6dHJhY2s6NVVsbnV1bFZBVm1tZXN3NFZ6cUhkRxICCAYSKgokc3BvdGlmeTp0cmFjazo1WFZFeDFwVFVSNFQ3QUJ0WG9HR3h4EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVaTGtHTEVZWURsZ2NEWEs2QTJ2WU8SAggGEioKJHNwb3RpZnk6dHJhY2s6NVpiNWxnSVliSWQ2eVZWZ083U2VWcBICCAYSKgokc3BvdGlmeTp0cmFjazo1YnpHb0gzYjhFVGk1UlJadHU2N3RqEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVjbzJkY3IxV25YSW9oRjM5NjBnbWwSAggGEioKJHNwb3RpZnk6dHJhY2s6NWQ1cjY5YUkyZmV3R1R5eFhsN0xPTBICCAYSKgokc3BvdGlmeTp0cmFjazo1ZjJ6WmF3QnRHQkV3MjRBQndlRXJ6EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVmYU1TQ3Y4N2F5ZVV6anRsdDFzcDkSAggGEioKJHNwb3RpZnk6dHJhY2s6NWZjQ3o0UTVSa1lDb3VXUHVBazUxSBICCAYSKgokc3BvdGlmeTp0cmFjazo1ZzlBdFNOWkZKVzA5cGRiTmQ2RTBUEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVnSVdBZFJoYUVPUVBCU3pZV1pQUW4SAggGEioKJHNwb3RpZnk6dHJhY2s6NWk2Z0hGWGc0YUxLNXh2YzJqSkpDNRICCAYSKgokc3BvdGlmeTp0cmFjazo1aXJCalc3T2VONllBb1I5WlVqTHREEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVqWllUVDhsU1hpVnprcGlCVFFHVGoSAggGEioKJHNwb3RpZnk6dHJhY2s6NWpoTXp3V0xnSkFUZ2dIN1lOZDd5dxICCAYSKgokc3BvdGlmeTp0cmFjazo1anVDdTRXRlRGUloyWGlsb3BBTVR5EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVrdkZCdTZqREpNRUNPcW1EN093VXgSAggGEioKJHNwb3RpZnk6dHJhY2s6NW1ZWGtKVEFrMkV2V3BFemt3Y2t0ZBICCAYSKgokc3BvdGlmeTp0cmFjazo1bXZGekpOOWwwNXRlV0JRY3V1WGZREgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVuQ3dqVVVzbUJ1TlpLbjlYdTEwT3MSAggGEioKJHNwb3RpZnk6dHJhY2s6NW80VTB3ZVVJQVhvbGppNHNFQW5qSRICCAYSKgokc3BvdGlmeTp0cmFjazo1b2RsWTUydTQzRjVCakJ5aHhnN3dnEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVzd0Q0ZW5aRGwxcjZ5blFzVEdISmESAggGEioKJHNwb3RpZnk6dHJhY2s6NXVoTzlzaXdUWXAzUEdZMVRUTnN6ZBICCAYSKgokc3BvdGlmeTp0cmFjazo1eHJ0enp6aWtwRzNCTGJvNHExWXVsEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjV6c01PRjN5V1Q0VTFWdzVlYU1RRkgSAggGEioKJHNwb3RpZnk6dHJhY2s6NjBBN0xHQW1LMFFyUmp5WXBLV3p1ZRICCAYSKgokc3BvdGlmeTp0cmFjazo2MGJhN1laM3lxYkNER0FrUE5YekJoEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjYyNjJMbW1STTFraEhYMUQ0eWs2TUESAggGEioKJHNwb3RpZnk6dHJhY2s6NjM4WnFEa1czamR3a2xhMTI5TzJNWhICCAYSKgokc3BvdGlmeTp0cmFjazo2M1E2eFVhRGlxSGZ3a3I4dDhjM0E5EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjY0MTA0WEoxUWxTWGRzTWtaSjh0bmQSAggGEioKJHNwb3RpZnk6dHJhY2s6NjRoYXloZnpvZGp3QnJRY1o2OVNWcBICCAYSKgokc3BvdGlmeTp0cmFjazo2NHE1RWZGS1I5aFlKMUZIcVNDbHhlEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjY2RWE1RGtMSDBPazZ3UjJ6dXFaY00SAggGEioKJHNwb3RpZnk6dHJhY2s6NjlTeTcyMDdkbml4WjZ3N1JTVjlLYhICCAYSKgokc3BvdGlmeTp0cmFjazo2OWhXNmJ1S0VJUm9nV25lNFBUUE81EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZBQjUzMFJmUEJoamFxaWtqYzA0QXkSAggGEioKJHNwb3RpZnk6dHJhY2s6NkFVYWtlVVdwQjdJSWFibEk3Y0padRICCAYSKgokc3BvdGlmeTp0cmFjazo2RUlNVWpRN1E4WnIyVnRJVWlrNEhlEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZFamFSOTUxOHBXS2FlRGJ3RXk3aHYSAggGEioKJHNwb3RpZnk6dHJhY2s6NkVzcmhOQmFibTlMeUlCclZsMTU3ZxICCAYSKgokc3BvdGlmeTp0cmFjazo2RjlqZHpYN0NmaXh2Q3NDa1c3enc5EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZGdmNNckx5SE93Ykg1VnlxVkgzOEESAggGEioKJHNwb3RpZnk6dHJhY2s6NkdJNUF3VjZyWGlBSXREQ0E4MjJOUxICCAYSKgokc3BvdGlmeTp0cmFjazo2SE4ydXl5TzZXbGJ5cDVxbm9vTnBuEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZJY1ZNOWlIVHNYNHNtMFhqNTRNQkYSAggGEioKJHNwb3RpZnk6dHJhY2s6NkpJbTM4S2JhREdmaTY1VkdFVERpORICCAYSKgokc3BvdGlmeTp0cmFjazo2SlFmUVhRMnhkWkQ2eDUxNnhOUkpJEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZNRURmakh4blZOY1ltSGUzbU02TDISAggGEioKJHNwb3RpZnk6dHJhY2s6NlNoQXhLNWVnVEZhYWxKTXR5MTVTaRICCAYSKgokc3BvdGlmeTp0cmFjazo2VGl0QnJ6WWhEMW1UeHFYQURGbzd2EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZXZUNOclZJSUdubVdIOUxYNU5wZUgSAggGEioKJHNwb3RpZnk6dHJhY2s6NllXUzd0OEtVVEtWUlBPcHQyVlJrZBICCAYSKgokc3BvdGlmeTp0cmFjazo2WWo4a1Z1VlIzVVB4eDlyNWVGRW9WEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZiN2UzYVFXME1NdjRjc2JVek9NSE8SAggGEioKJHNwb3RpZnk6dHJhY2s6NmMxbWYxa2FvZUUzNkRkMndVZFgxUBICCAYSKgokc3BvdGlmeTp0cmFjazo2ZEdzQlJ1YXZ1bUJzNUJnaGNYRjNEEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZkVkR5TXVkN1AzZWFVTThHV2FnY2MSAggGEioKJHNwb3RpZnk6dHJhY2s6NmRnV1dBczV5aFdQT3R2RTF6dW9RMRICCAYSKgokc3BvdGlmeTp0cmFjazo2ZnZidzB1UVBZZDlSdEJ3N1dWZ2IzEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZoZVQ0aW9iZ2JzNlJTWW5lbjMxTDYSAggGEioKJHNwb3RpZnk6dHJhY2s6Nmh5dHBzUWxwN2REcnF5SE42V3ROThICCAYSKgokc3BvdGlmeTp0cmFjazo2anVMYWR1RDRTVENVRFdUMEFZdW40EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZsV1k0amk5VDB0cEZVMnhiblJDMXASAggGEioKJHNwb3RpZnk6dHJhY2s6Nm1VUVVzZnJFbHB3ZlhQWFRwSldiRBICCAYSKgokc3BvdGlmeTp0cmFjazo2bmZVN05Eajg4SVlkWGNoVjdYYjBMEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZub3pETHhlTDBURTRNUzlHcVlVMXYSAggGEioKJHNwb3RpZnk6dHJhY2s6Nm9GS2hkclYwSjR1dXdNUVllN1NPNhICCAYSKgokc3BvdGlmeTp0cmFjazo2cGg5Q3d1emduQ2lpOE5zSjFKSjBHEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZxYUdZUG5RVGRDTFNTcWVDZEpBNTUSAggGEioKJHNwb3RpZnk6dHJhY2s6NnM4bkhYVEpWcUZqWEU0eVZaUERIUhICCAYSKgokc3BvdGlmeTp0cmFjazo2c2k3MXN1cG5CVWhkZGpSMkZKYzJMEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZ0QVB3MVJ0dDNTR0VPbTZvaFlpOGwSAggGEioKJHNwb3RpZnk6dHJhY2s6NnZ0NFI0cTVZTDRNMmN4bDdvNnBUZRICCAYSKgokc3BvdGlmeTp0cmFjazo2d3Y3bkd2aGRGTFpENFhtRkV0MzNDEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZ4NTNPT0hZOTdvd2hPdm50aE5yRmESAggGEioKJHNwb3RpZnk6dHJhY2s6NnlLMkFHTDZvYW1xNkZQOGlxbU9CdxICCAYSKgokc3BvdGlmeTp0cmFjazo2eWZHZXIxVEtweE9qaFNkNWVMMERMEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZ6QWlSS3ZBTWxYSHhFdHlPNHl4SU8SAggGEioKJHNwb3RpZnk6dHJhY2s6NzEyUG03RENhOGxMOGRHWjdMZFhRUxICCAYSKgokc3BvdGlmeTp0cmFjazo3MUtRdm9LRWRsMjhVN3dGdDZlR0l3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjcxUXBaSm00OGVxcWRFQzFwVUZad04SAggGEioKJHNwb3RpZnk6dHJhY2s6NzFubmhja1VQZnVwaHZ5WUp4NmwwMRICCAYSKgokc3BvdGlmeTp0cmFjazo3MlZ1MGRoVmxwanRkUGRsaTIyNE5mEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjcyaE5lcGp2ZXBrOXBLRWNuR09zMmYSAggGEioKJHNwb3RpZnk6dHJhY2s6NzNPWlQxWGdMbGVEd3BlcnFHaldINBICCAYSKgokc3BvdGlmeTp0cmFjazo3M3FDUGd3cEZ3QWU5TDJRdDBEcmgxEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjc1MG9hUU5kVXRvS0p2OUlLZGg4WFoSAggGEioKJHNwb3RpZnk6dHJhY2s6NzV2ZXBrc2V0aEc3R3JSbjgxNVpZSBICCAYSKgokc3BvdGlmeTp0cmFjazo3NlZNeGJtUjZJSm84YlBWdmFRYUY0EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjc4V2daWVVrMTBrY0VwYkxzOG5mMzgSAggGEioKJHNwb3RpZnk6dHJhY2s6NzlidXN6cnR1NDBGYnhGZ1RSaG9LdBICCAYSKgokc3BvdGlmeTp0cmFjazo3RXd6NmJKOTd2VXFrNUhka3ZndUZREgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdHSVZiNWNKYTh5R3pNamRoZjdQd1MSAggGEioKJHNwb3RpZnk6dHJhY2s6N0dOUlVzVTNNNFhORERCOXhsZTVEehICCAYSKgokc3BvdGlmeTp0cmFjazo3R1RDRnMwcXUyNEVDODJ0ZFVSYlRsEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdHd05ERnl4dnBIQWQ0bDFJZlVEbXISAggGEioKJHNwb3RpZnk6dHJhY2s6N0g1cjE5d242RnRrRmZlZHo1S0pXURICCAYSKgokc3BvdGlmeTp0cmFjazo3STVXVDdEdHB3U0FoRWVETHBaRWZtEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdJN1RUZktjRERBZVNmNkhQZ2JkUFQSAggGEioKJHNwb3RpZnk6dHJhY2s6N0xwTUczQUVhSUpnczYySFFoQWE5MRICCAYSKgokc3BvdGlmeTp0cmFjazo3TWoxa1FMYXF1NlJyNnJ3QUlKUVFoEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdNeWJzdFVnQ0JVVnlQVjh0enNCMVUSAggGEioKJHNwb3RpZnk6dHJhY2s6N2J5TGdweDlZMVBYbENZOUFpNDEwZxICCAYSKgokc3BvdGlmeTp0cmFjazo3ZFU2WnJEM3NUOXF5SEU1bVg1Q2pjEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdkazdqeEtCdW4xSlEycFBQQnhEWWwSAggGEioKJHNwb3RpZnk6dHJhY2s6N2VQcFFlcE9wdFoxTTlqUlJ5ZEhzWhICCAYSKgokc3BvdGlmeTp0cmFjazo3aG00QlluY2VDdXhsaW9MYUtHaXlXEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdpWEhMdFBvc2JIdmdsVlNKNHJ4THESAggGEioKJHNwb3RpZnk6dHJhY2s6N2lzT2EwWVdtbmdxQXE3aDNSY1pqMRICCAYSKgokc3BvdGlmeTp0cmFjazo3bW1KcmpFVFFtYjBZNUdDM0ZRZTFqEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdyTHZzQU8xeWI3RWx4UGhrejYwcWgSAggGEioKJHNwb3RpZnk6dHJhY2s6N3Jpa3VrVm1rQnVoa0c4S1JRR3huRhICCAYSKgokc3BvdGlmeTp0cmFjazo3c3A1aVRRakI3R0hYWDRUS3JoT2FPEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjd0SThkUnVIMlljNlJ1b1RqeG80ZFUSAggGEioKJHNwb3RpZnk6dHJhY2s6N3ZXZGpvU2FLSmRCZ21Ba1E4Mks5ehICCAYSKgokc3BvdGlmeTp0cmFjazo3eU02M1pleGFkbnRCTmdLWTNIWFFGEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjd6eHZFZ3RQaktxVjlvUUFtc0x1aEsSAggG
var base64 =
    "Ch8KAk5MEgdwcmVtaXVtGhBqrCiHbAl1CmsMusvHAnw1EioKJHNwb3RpZnk6dHJhY2s6NFpoSjVOOEVyNENmcGFOYWtVUVRrUBICCAYSKgokc3BvdGlmeTp0cmFjazo0Wm5reWdvV0x6Y0diUVlDbTNsa2FlEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRhN1ZnWXZLbWo0UTlkYzN2UnVvREMSAggGEioKJHNwb3RpZnk6dHJhY2s6NGFKelBNekVUYTJrU20xR3o4UGxCeBICCAYSKgokc3BvdGlmeTp0cmFjazo0YjMwcnhlNGt4ak5sOFlwRTE3U2V3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRiNTBYYkhramhGNzNqNnZKYXBSSkYSAggGEioKJHNwb3RpZnk6dHJhY2s6NGNlV21LUlBlM1BHWHo0WnlFdDNsZRICCAYSKgokc3BvdGlmeTp0cmFjazo0ZUZUaDFvcExTNXdBTkRtWks5Z2hDEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRld2F6UUxYRlREQzhYdkNiaHZ0WHMSAggGEioKJHNwb3RpZnk6dHJhY2s6NGV5Qml3c2FHQlJDakFDR1pLWnNmNxICCAYSKgokc3BvdGlmeTp0cmFjazo0ZmozSTZVT2IzN3JPdHRqSmFja2RqEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRnTVBsSEhBak9RblVyaHN1cUhpdm4SAggGEioKJHNwb3RpZnk6dHJhY2s6NGhwR0hvSnVKVHRBcXE5cGtldkxwNhICCAYSKgokc3BvdGlmeTp0cmFjazo0aUpaMTJndmN1bmY4MGd5bTdxRU0yEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRpbmNrVklmT1hYN2VpSVNDMDFVeFoSAggGEioKJHNwb3RpZnk6dHJhY2s6NGl0ZE92ZzZWOGhqVE9RVWVhR0hXdBICCAYSKgokc3BvdGlmeTp0cmFjazo0a3ZLWTQzd0J6UWFoeFNhdlBZVUl2EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRsNWU0RzFSenJmV1dGZ2Vob0VnQUgSAggGEioKJHNwb3RpZnk6dHJhY2s6NG00YVFMaVBiV0Z5RTA3eFJvSlBoYxICCAYSKgokc3BvdGlmeTp0cmFjazo0bXFmZTlYcmdFT1Nzb2Z2cTVNeWpSEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRuZHhDcnRsNzRsZ09kRjZMejdiSXESAggGEioKJHNwb3RpZnk6dHJhY2s6NG56QlNUOUpkWkl5OXFmaWxyOTNQbxICCAYSKgokc3BvdGlmeTp0cmFjazo0b0hROG45T0tRMzU5OWU4bm9DckRYEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRxM2JpYVFRb0FEc3BWMTZsYnNmUEgSAggGEioKJHNwb3RpZnk6dHJhY2s6NHFOSzl6YlJmbzAzU0dqYXNtTHlhRxICCAYSKgokc3BvdGlmeTp0cmFjazo0cWRlNDFLTmZKdjJUeXJLQzFrdWc3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjRxd3R4cGhRUzJHZlBpRGI2TUpKa0sSAggGEioKJHNwb3RpZnk6dHJhY2s6NHNUalVZaklDMDJSa05hMUE4cldqRRICCAYSKgokc3BvdGlmeTp0cmFjazo0dDVqb1prZGxYbHZ6TFhKYmtncHBKEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjR3SjVRcTBqQk40YWp5N291WklWMWMSAggGEioKJHNwb3RpZnk6dHJhY2s6NHhldWdCNU1xV2gwand2WFpQeGFocRICCAYSKgokc3BvdGlmeTp0cmFjazo0eHB4MEJsZmFUZDY0eWNpRldsTTR3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjR5Tms5aXo5V1ZKaWtSRmxlM1hFdm4SAggGEioKJHNwb3RpZnk6dHJhY2s6NHlzb3dLN2hKZ0kxUVI0dFA1QUQ0dBICCAYSKgokc3BvdGlmeTp0cmFjazo0eXR5THBJd1VYYmRGc05PdmdObm1QEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjUyVGR1dU9FNHJWbmhMREFHQjRRUEUSAggGEioKJHNwb3RpZnk6dHJhY2s6NTJwNVJ0RWFUWHgxdTF1ZHJ4OEZxchICCAYSKgokc3BvdGlmeTp0cmFjazo1MnR1bXdFZENBcDdUckoxUUxOQWhvEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjUzVDVtWnVxQWp2bTBwaW5VZndJWHISAggGEioKJHNwb3RpZnk6dHJhY2s6NTVvY0pQUnhXdWVnbzRwa0ZQVVpDYhICCAYSKgokc3BvdGlmeTp0cmFjazo1N2RxUVE3Nzl5Y1FEUE9jZzNkNWRVEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjU4NGhUT08yMEIyV0tLOFBqUEIxR3cSAggGEioKJHNwb3RpZnk6dHJhY2s6NUVoMW5qN0lqVjlsd3BjS0FraWR5WRICCAYSKgokc3BvdGlmeTp0cmFjazo1RWp2bHlqTXdxbWFiWGdGREQ4RDJ4EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVGS2RXVDVBN3ZEVEVuUGlIcnJ1RlkSAggGEioKJHNwb3RpZnk6dHJhY2s6NUZWYnZ0dGpFdlE4cjJCZ1VjSmdOZxICCAYSKgokc3BvdGlmeTp0cmFjazo1R0dFZE5FdHpvNktMVFZSTFdrZFdhEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVKcGZjdWZyME1lQmVvWmRvS0s4dXkSAggGEioKJHNwb3RpZnk6dHJhY2s6NUpwZnRVSGVVengzeldFNnJadGtpNRICCAYSKgokc3BvdGlmeTp0cmFjazo1S2JwY2QzaE9xdTRaUkFKTkFqSWNnEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVMOG1SZ1I3RXl3Zk1icENBdWRkTlMSAggGEioKJHNwb3RpZnk6dHJhY2s6NUxFTXNKOERBc0NxWU9sbUpjaUZTWRICCAYSKgokc3BvdGlmeTp0cmFjazo1THZGYUtzMVFOMm5SNjVoNHRKTjRSEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVNR1pQbjdRV0dEM0RUbVB5cnBqNzkSAggGEioKJHNwb3RpZnk6dHJhY2s6NVBkMUszMXlnTEpqZ2JwQUU2aWNyNBICCAYSKgokc3BvdGlmeTp0cmFjazo1UktuSEwwcGNUNWZQTkIzOG9MNHd2EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVTaDJwSlQzVldUdmtRT1hQQWFSaUMSAggGEioKJHNwb3RpZnk6dHJhY2s6NVRlRElRcnB3V3RMV2FGZnpMSDBoaBICCAYSKgokc3BvdGlmeTp0cmFjazo1VHV6UTQ0bFBXVENLYmZYYk5JRVhnEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVVZUl3Y1VJS1RWUHFCbnVYbmhtQkQSAggGEioKJHNwb3RpZnk6dHJhY2s6NVVsbnV1bFZBVm1tZXN3NFZ6cUhkRxICCAYSKgokc3BvdGlmeTp0cmFjazo1WFZFeDFwVFVSNFQ3QUJ0WG9HR3h4EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVaTGtHTEVZWURsZ2NEWEs2QTJ2WU8SAggGEioKJHNwb3RpZnk6dHJhY2s6NVpiNWxnSVliSWQ2eVZWZ083U2VWcBICCAYSKgokc3BvdGlmeTp0cmFjazo1YnpHb0gzYjhFVGk1UlJadHU2N3RqEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVjbzJkY3IxV25YSW9oRjM5NjBnbWwSAggGEioKJHNwb3RpZnk6dHJhY2s6NWQ1cjY5YUkyZmV3R1R5eFhsN0xPTBICCAYSKgokc3BvdGlmeTp0cmFjazo1ZjJ6WmF3QnRHQkV3MjRBQndlRXJ6EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVmYU1TQ3Y4N2F5ZVV6anRsdDFzcDkSAggGEioKJHNwb3RpZnk6dHJhY2s6NWZjQ3o0UTVSa1lDb3VXUHVBazUxSBICCAYSKgokc3BvdGlmeTp0cmFjazo1ZzlBdFNOWkZKVzA5cGRiTmQ2RTBUEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVnSVdBZFJoYUVPUVBCU3pZV1pQUW4SAggGEioKJHNwb3RpZnk6dHJhY2s6NWk2Z0hGWGc0YUxLNXh2YzJqSkpDNRICCAYSKgokc3BvdGlmeTp0cmFjazo1aXJCalc3T2VONllBb1I5WlVqTHREEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVqWllUVDhsU1hpVnprcGlCVFFHVGoSAggGEioKJHNwb3RpZnk6dHJhY2s6NWpoTXp3V0xnSkFUZ2dIN1lOZDd5dxICCAYSKgokc3BvdGlmeTp0cmFjazo1anVDdTRXRlRGUloyWGlsb3BBTVR5EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVrdkZCdTZqREpNRUNPcW1EN093VXgSAggGEioKJHNwb3RpZnk6dHJhY2s6NW1ZWGtKVEFrMkV2V3BFemt3Y2t0ZBICCAYSKgokc3BvdGlmeTp0cmFjazo1bXZGekpOOWwwNXRlV0JRY3V1WGZREgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVuQ3dqVVVzbUJ1TlpLbjlYdTEwT3MSAggGEioKJHNwb3RpZnk6dHJhY2s6NW80VTB3ZVVJQVhvbGppNHNFQW5qSRICCAYSKgokc3BvdGlmeTp0cmFjazo1b2RsWTUydTQzRjVCakJ5aHhnN3dnEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjVzd0Q0ZW5aRGwxcjZ5blFzVEdISmESAggGEioKJHNwb3RpZnk6dHJhY2s6NXVoTzlzaXdUWXAzUEdZMVRUTnN6ZBICCAYSKgokc3BvdGlmeTp0cmFjazo1eHJ0enp6aWtwRzNCTGJvNHExWXVsEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjV6c01PRjN5V1Q0VTFWdzVlYU1RRkgSAggGEioKJHNwb3RpZnk6dHJhY2s6NjBBN0xHQW1LMFFyUmp5WXBLV3p1ZRICCAYSKgokc3BvdGlmeTp0cmFjazo2MGJhN1laM3lxYkNER0FrUE5YekJoEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjYyNjJMbW1STTFraEhYMUQ0eWs2TUESAggGEioKJHNwb3RpZnk6dHJhY2s6NjM4WnFEa1czamR3a2xhMTI5TzJNWhICCAYSKgokc3BvdGlmeTp0cmFjazo2M1E2eFVhRGlxSGZ3a3I4dDhjM0E5EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjY0MTA0WEoxUWxTWGRzTWtaSjh0bmQSAggGEioKJHNwb3RpZnk6dHJhY2s6NjRoYXloZnpvZGp3QnJRY1o2OVNWcBICCAYSKgokc3BvdGlmeTp0cmFjazo2NHE1RWZGS1I5aFlKMUZIcVNDbHhlEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjY2RWE1RGtMSDBPazZ3UjJ6dXFaY00SAggGEioKJHNwb3RpZnk6dHJhY2s6NjlTeTcyMDdkbml4WjZ3N1JTVjlLYhICCAYSKgokc3BvdGlmeTp0cmFjazo2OWhXNmJ1S0VJUm9nV25lNFBUUE81EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZBQjUzMFJmUEJoamFxaWtqYzA0QXkSAggGEioKJHNwb3RpZnk6dHJhY2s6NkFVYWtlVVdwQjdJSWFibEk3Y0padRICCAYSKgokc3BvdGlmeTp0cmFjazo2RUlNVWpRN1E4WnIyVnRJVWlrNEhlEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZFamFSOTUxOHBXS2FlRGJ3RXk3aHYSAggGEioKJHNwb3RpZnk6dHJhY2s6NkVzcmhOQmFibTlMeUlCclZsMTU3ZxICCAYSKgokc3BvdGlmeTp0cmFjazo2RjlqZHpYN0NmaXh2Q3NDa1c3enc5EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZGdmNNckx5SE93Ykg1VnlxVkgzOEESAggGEioKJHNwb3RpZnk6dHJhY2s6NkdJNUF3VjZyWGlBSXREQ0E4MjJOUxICCAYSKgokc3BvdGlmeTp0cmFjazo2SE4ydXl5TzZXbGJ5cDVxbm9vTnBuEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZJY1ZNOWlIVHNYNHNtMFhqNTRNQkYSAggGEioKJHNwb3RpZnk6dHJhY2s6NkpJbTM4S2JhREdmaTY1VkdFVERpORICCAYSKgokc3BvdGlmeTp0cmFjazo2SlFmUVhRMnhkWkQ2eDUxNnhOUkpJEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZNRURmakh4blZOY1ltSGUzbU02TDISAggGEioKJHNwb3RpZnk6dHJhY2s6NlNoQXhLNWVnVEZhYWxKTXR5MTVTaRICCAYSKgokc3BvdGlmeTp0cmFjazo2VGl0QnJ6WWhEMW1UeHFYQURGbzd2EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZXZUNOclZJSUdubVdIOUxYNU5wZUgSAggGEioKJHNwb3RpZnk6dHJhY2s6NllXUzd0OEtVVEtWUlBPcHQyVlJrZBICCAYSKgokc3BvdGlmeTp0cmFjazo2WWo4a1Z1VlIzVVB4eDlyNWVGRW9WEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZiN2UzYVFXME1NdjRjc2JVek9NSE8SAggGEioKJHNwb3RpZnk6dHJhY2s6NmMxbWYxa2FvZUUzNkRkMndVZFgxUBICCAYSKgokc3BvdGlmeTp0cmFjazo2ZEdzQlJ1YXZ1bUJzNUJnaGNYRjNEEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZkVkR5TXVkN1AzZWFVTThHV2FnY2MSAggGEioKJHNwb3RpZnk6dHJhY2s6NmRnV1dBczV5aFdQT3R2RTF6dW9RMRICCAYSKgokc3BvdGlmeTp0cmFjazo2ZnZidzB1UVBZZDlSdEJ3N1dWZ2IzEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZoZVQ0aW9iZ2JzNlJTWW5lbjMxTDYSAggGEioKJHNwb3RpZnk6dHJhY2s6Nmh5dHBzUWxwN2REcnF5SE42V3ROThICCAYSKgokc3BvdGlmeTp0cmFjazo2anVMYWR1RDRTVENVRFdUMEFZdW40EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZsV1k0amk5VDB0cEZVMnhiblJDMXASAggGEioKJHNwb3RpZnk6dHJhY2s6Nm1VUVVzZnJFbHB3ZlhQWFRwSldiRBICCAYSKgokc3BvdGlmeTp0cmFjazo2bmZVN05Eajg4SVlkWGNoVjdYYjBMEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZub3pETHhlTDBURTRNUzlHcVlVMXYSAggGEioKJHNwb3RpZnk6dHJhY2s6Nm9GS2hkclYwSjR1dXdNUVllN1NPNhICCAYSKgokc3BvdGlmeTp0cmFjazo2cGg5Q3d1emduQ2lpOE5zSjFKSjBHEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZxYUdZUG5RVGRDTFNTcWVDZEpBNTUSAggGEioKJHNwb3RpZnk6dHJhY2s6NnM4bkhYVEpWcUZqWEU0eVZaUERIUhICCAYSKgokc3BvdGlmeTp0cmFjazo2c2k3MXN1cG5CVWhkZGpSMkZKYzJMEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZ0QVB3MVJ0dDNTR0VPbTZvaFlpOGwSAggGEioKJHNwb3RpZnk6dHJhY2s6NnZ0NFI0cTVZTDRNMmN4bDdvNnBUZRICCAYSKgokc3BvdGlmeTp0cmFjazo2d3Y3bkd2aGRGTFpENFhtRkV0MzNDEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZ4NTNPT0hZOTdvd2hPdm50aE5yRmESAggGEioKJHNwb3RpZnk6dHJhY2s6NnlLMkFHTDZvYW1xNkZQOGlxbU9CdxICCAYSKgokc3BvdGlmeTp0cmFjazo2eWZHZXIxVEtweE9qaFNkNWVMMERMEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjZ6QWlSS3ZBTWxYSHhFdHlPNHl4SU8SAggGEioKJHNwb3RpZnk6dHJhY2s6NzEyUG03RENhOGxMOGRHWjdMZFhRUxICCAYSKgokc3BvdGlmeTp0cmFjazo3MUtRdm9LRWRsMjhVN3dGdDZlR0l3EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjcxUXBaSm00OGVxcWRFQzFwVUZad04SAggGEioKJHNwb3RpZnk6dHJhY2s6NzFubmhja1VQZnVwaHZ5WUp4NmwwMRICCAYSKgokc3BvdGlmeTp0cmFjazo3MlZ1MGRoVmxwanRkUGRsaTIyNE5mEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjcyaE5lcGp2ZXBrOXBLRWNuR09zMmYSAggGEioKJHNwb3RpZnk6dHJhY2s6NzNPWlQxWGdMbGVEd3BlcnFHaldINBICCAYSKgokc3BvdGlmeTp0cmFjazo3M3FDUGd3cEZ3QWU5TDJRdDBEcmgxEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjc1MG9hUU5kVXRvS0p2OUlLZGg4WFoSAggGEioKJHNwb3RpZnk6dHJhY2s6NzV2ZXBrc2V0aEc3R3JSbjgxNVpZSBICCAYSKgokc3BvdGlmeTp0cmFjazo3NlZNeGJtUjZJSm84YlBWdmFRYUY0EgIIBhIqCiRzcG90aWZ5OnRyYWNrOjc4V2daWVVrMTBrY0VwYkxzOG5mMzgSAggGEioKJHNwb3RpZnk6dHJhY2s6NzlidXN6cnR1NDBGYnhGZ1RSaG9LdBICCAYSKgokc3BvdGlmeTp0cmFjazo3RXd6NmJKOTd2VXFrNUhka3ZndUZREgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdHSVZiNWNKYTh5R3pNamRoZjdQd1MSAggGEioKJHNwb3RpZnk6dHJhY2s6N0dOUlVzVTNNNFhORERCOXhsZTVEehICCAYSKgokc3BvdGlmeTp0cmFjazo3R1RDRnMwcXUyNEVDODJ0ZFVSYlRsEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdHd05ERnl4dnBIQWQ0bDFJZlVEbXISAggGEioKJHNwb3RpZnk6dHJhY2s6N0g1cjE5d242RnRrRmZlZHo1S0pXURICCAYSKgokc3BvdGlmeTp0cmFjazo3STVXVDdEdHB3U0FoRWVETHBaRWZtEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdJN1RUZktjRERBZVNmNkhQZ2JkUFQSAggGEioKJHNwb3RpZnk6dHJhY2s6N0xwTUczQUVhSUpnczYySFFoQWE5MRICCAYSKgokc3BvdGlmeTp0cmFjazo3TWoxa1FMYXF1NlJyNnJ3QUlKUVFoEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdNeWJzdFVnQ0JVVnlQVjh0enNCMVUSAggGEioKJHNwb3RpZnk6dHJhY2s6N2J5TGdweDlZMVBYbENZOUFpNDEwZxICCAYSKgokc3BvdGlmeTp0cmFjazo3ZFU2WnJEM3NUOXF5SEU1bVg1Q2pjEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdkazdqeEtCdW4xSlEycFBQQnhEWWwSAggGEioKJHNwb3RpZnk6dHJhY2s6N2VQcFFlcE9wdFoxTTlqUlJ5ZEhzWhICCAYSKgokc3BvdGlmeTp0cmFjazo3aG00QlluY2VDdXhsaW9MYUtHaXlXEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdpWEhMdFBvc2JIdmdsVlNKNHJ4THESAggGEioKJHNwb3RpZnk6dHJhY2s6N2lzT2EwWVdtbmdxQXE3aDNSY1pqMRICCAYSKgokc3BvdGlmeTp0cmFjazo3bW1KcmpFVFFtYjBZNUdDM0ZRZTFqEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjdyTHZzQU8xeWI3RWx4UGhrejYwcWgSAggGEioKJHNwb3RpZnk6dHJhY2s6N3Jpa3VrVm1rQnVoa0c4S1JRR3huRhICCAYSKgokc3BvdGlmeTp0cmFjazo3c3A1aVRRakI3R0hYWDRUS3JoT2FPEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjd0SThkUnVIMlljNlJ1b1RqeG80ZFUSAggGEioKJHNwb3RpZnk6dHJhY2s6N3ZXZGpvU2FLSmRCZ21Ba1E4Mks5ehICCAYSKgokc3BvdGlmeTp0cmFjazo3eU02M1pleGFkbnRCTmdLWTNIWFFGEgIIBhIqCiRzcG90aWZ5OnRyYWNrOjd6eHZFZ3RQaktxVjlvUUFtc0x1aEsSAggG";

var http = new HttpClient();
using var httpRequest = new HttpRequestMessage(HttpMethod.Post,
    "https://gew4-spclient.spotify.com/extended-metadata/v0/extended-metadata");

httpRequest.Headers.TryAddWithoutValidation("User-Agent", "Spotify/128600502 Win32_x86_64/Windows 10 (10.0.26200; x64; AppX)");
httpRequest.Headers.TryAddWithoutValidation("Accept-Language", "en");
httpRequest.Headers.TryAddWithoutValidation("App-Platform", "Win32_x86_64");
httpRequest.Headers.TryAddWithoutValidation("client-feature-id", "collection");
httpRequest.Headers.TryAddWithoutValidation("client-token", "AAAwLhog0baeJppBvmluMh79N32AsGEBm/hrWMZLMptaAFDoFkFzfBdQHnlAujqP+OBaDYVVCTyorujpbZKEwR8MECqOdKXvoQPEjOJTlANudYeLRxa7iFxWeOazUrYSftRy0/pv4DIjbZDRa2NbDrCxJwvIDktzJcrCGSHV3vWP6XLI4NpOSmWEC1LNKF5QlSYuCIE090PR++4wqZzSLvKyQh5VQUsPuGKm5gzj0U5bAi9BOOJSFEwCvfFy82H4HmrW3vt20cVbF2Mlbw6EztbhN2W0IRRr");
httpRequest.Headers.TryAddWithoutValidation("Spotify-App-Version", "128600502");
//User-Agent: Spotify/128600502 Win32_x86_64/Windows 10 (10.0.26200; x64; AppX)
//Accept-Language: en
//App-Platform: Win32_x86_64
//client-feature-id: collection
//client-token: AAAwLhog0baeJppBvmluMh79N32AsGEBm/hrWMZLMptaAFDoFkFzfBdQHnlAujqP+OBaDYVVCTyorujpbZKEwR8MECqOdKXvoQPEjOJTlANudYeLRxa7iFxWeOazUrYSftRy0/pv4DIjbZDRa2NbDrCxJwvIDktzJcrCGSHV3vWP6XLI4NpOSmWEC1LNKF5QlSYuCIE090PR++4wqZzSLvKyQh5VQUsPuGKm5gzj0U5bAi9BOOJSFEwCvfFy82H4HmrW3vt20cVbF2Mlbw6EztbhN2W0IRRr
//Spotify-App-Version: 128600502
//request = BatchedEntityRequest.Parser.ParseFrom(ByteString.FromBase64(base64));
var content = new ByteArrayContent(request.ToByteArray());
httpRequest.Content = content;
httpRequest.Content.Headers.ContentType = new MediaTypeHeaderValue("application/protobuf");
var response = await http.SendAsync(httpRequest);
var data = await response.Content.ReadAsByteArrayAsync();
var responseData = BatchedExtensionResponse.Parser.ParseFrom(data);
var item = responseData.ExtendedMetadata.First().ExtensionData.First().ExtensionData.Value;
var descriptorData = ExtensionDescriptorData.Parser.ParseFrom(item);

// Create SpectreUI instance (will be configured with Serilog later)
using var spectreUI = new SpectreUI();

// Configure Serilog with SpectreUI sink
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .WriteTo.SpectreUI(spectreUI, LogEventLevel.Debug)
    .CreateLogger();

// Setup Microsoft.Extensions.Logging with Serilog
using var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddSerilog(Log.Logger, dispose: false);
    builder.SetMinimumLevel(LogLevel.Debug);
});

var logger = loggerFactory.CreateLogger<Program>();
var sessionLogger = loggerFactory.CreateLogger("Wavee.Core.Session.Session");

// Setup dependency injection with HttpClient
var services = new ServiceCollection();
services.AddHttpClient("Wavee", client => { client.Timeout = TimeSpan.FromSeconds(30); });
var serviceProvider = services.BuildServiceProvider();
var httpClientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

// Setup credentials cache
var credentialsCache = new CredentialsCache(logger: loggerFactory.CreateLogger<CredentialsCache>());

try
{
    // Show startup banner
    AnsiConsole.Write(new FigletText("Wavee").Color(Color.Green));
    AnsiConsole.MarkupLine("[dim]Spotify Connect Client[/]");
    AnsiConsole.WriteLine();

    // 1. Create session configuration
    var deviceId = GetOrCreateDeviceId();
    AnsiConsole.MarkupLine($"[dim]Device ID:[/] {deviceId[..8]}...");

    var config = new SessionConfig
    {
        DeviceId = deviceId,
        DeviceName = "Wavee Console",
        DeviceType = DeviceType.Computer
    };

    // 2. Try to load stored credentials
    var lastUsername = await credentialsCache.LoadLastUsernameAsync();
    var storedCredentials = await credentialsCache.LoadCredentialsAsync(lastUsername);

    Credentials credentials;
    if (storedCredentials != null)
    {
        AnsiConsole.MarkupLine("[green]Found stored credentials[/] - skipping OAuth");
        credentials = storedCredentials;
    }
    else
    {
        AnsiConsole.MarkupLine("[yellow]No stored credentials[/] - OAuth required");
        AnsiConsole.WriteLine();

        var oauthLogger = loggerFactory.CreateLogger("OAuth");
        var accessToken = await GetAccessTokenAsync(config.GetClientId(), oauthLogger);
        credentials = Credentials.WithAccessToken(accessToken);
    }

    // 3. Create and connect session
    AnsiConsole.MarkupLine("[dim]Creating session...[/]");
    await using var session = Session.Create(config, httpClientFactory, sessionLogger);

    // 4. Connect with status spinner
    await AnsiConsole.Status()
        .Spinner(Spinner.Known.Dots)
        .StartAsync("Connecting to Spotify...",
            async ctx => { await session.ConnectAsync(credentials, credentialsCache); });

    var userData = session.GetUserData();
    if (userData != null)
    {
        AnsiConsole.MarkupLine($"[green]Connected![/] Username: [bold]{userData.Username}[/]");

        // Get country and account info
        await AnsiConsole.Status()
            .Spinner(Spinner.Known.Dots)
            .StartAsync("Fetching account info...", async ctx =>
            {
                var countryCode = await session.GetCountryCodeAsync();
                var accountType = await session.GetAccountTypeAsync();
                AnsiConsole.MarkupLine($"[dim]Country:[/] {countryCode}  [dim]Account:[/] {accountType}");
            });
    }

    AnsiConsole.WriteLine();
    AnsiConsole.MarkupLine("[dim]Starting interactive console...[/]");
    AnsiConsole.MarkupLine("[dim]Press any key to continue[/]");
    System.Console.ReadKey(intercept: true);

    // 5. Run interactive Connect console
    var httpClient = httpClientFactory.CreateClient("Wavee");
    var audioPipelineLogger = loggerFactory.CreateLogger("Wavee.Audio.Pipeline");

    // Initialize UI with device info
    spectreUI.UpdateDevice(config.DeviceName, config.DeviceId, false);

    await using var connectConsole = new ConnectConsole(session, httpClient, spectreUI, audioPipelineLogger);
    await connectConsole.RunAsync();

    // 6. Cleanup
    Log.Information("Session closed successfully.");
}
catch (OAuthException ex)
{
    AnsiConsole.MarkupLine($"[red]OAuth failed:[/] {ex.Message}");
    AnsiConsole.MarkupLine($"[dim]Reason:[/] {ex.Reason}");
}
catch (AuthenticationException ex)
{
    AnsiConsole.MarkupLine($"[red]Authentication failed:[/] {ex.Message}");
    AnsiConsole.MarkupLine($"[dim]Reason:[/] {ex.Reason}");
}
catch (SessionException ex)
{
    AnsiConsole.MarkupLine($"[red]Session error:[/] {ex.Message}");
    AnsiConsole.MarkupLine($"[dim]Reason:[/] {ex.Reason}");
}
catch (Exception ex)
{
    AnsiConsole.Write(ex.ToString());
}

AnsiConsole.WriteLine();
AnsiConsole.MarkupLine("[dim]Press any key to exit...[/]");
System.Console.ReadKey(intercept: true);

// Helper methods

static async Task<string> GetAccessTokenAsync(string clientId, Microsoft.Extensions.Logging.ILogger logger)
{
    var flow = AnsiConsole.Prompt(
        new SelectionPrompt<OAuthFlow>()
            .Title("Select [green]OAuth authorization method[/]:")
            .AddChoices(OAuthFlow.AuthorizationCode, OAuthFlow.DeviceCode)
            .UseConverter(f => f switch
            {
                OAuthFlow.AuthorizationCode => "Authorization Code Flow (opens browser)",
                OAuthFlow.DeviceCode => "Device Code Flow (enter code manually)",
                _ => f.ToString()
            }));

    AnsiConsole.WriteLine();

    OAuthToken newToken;

    if (flow == OAuthFlow.DeviceCode)
    {
        AnsiConsole.MarkupLine("[cyan]Using Device Code Flow[/]");
        AnsiConsole.MarkupLine("[dim]You'll need to visit a URL and enter a code to authorize.[/]");
        AnsiConsole.WriteLine();

        var client = OAuthClient.CreateCustom(
            clientId,
            ["streaming", "user-read-playback-state", "user-modify-playback-state"],
            flow: OAuthFlow.DeviceCode,
            logger: logger);

        newToken = await client.GetAccessTokenAsync();
    }
    else
    {
        AnsiConsole.MarkupLine("[cyan]Using Authorization Code Flow[/]");
        AnsiConsole.MarkupLine("[dim]Your browser will open to authorize Wavee.[/]");
        AnsiConsole.WriteLine();

        var client = OAuthClient.CreateCustom(
            clientId,
            ["streaming", "user-read-playback-state", "user-modify-playback-state"],
            flow: OAuthFlow.AuthorizationCode,
            openBrowser: true,
            logger: logger);

        newToken = await client.GetAccessTokenAsync();
    }

    AnsiConsole.MarkupLine("[green]Successfully obtained access token![/]");
    return newToken.AccessToken;
}

static string GetOrCreateDeviceId()
{
    var deviceIdPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
        "Wavee",
        "device_id.txt"
    );

    if (File.Exists(deviceIdPath))
    {
        return File.ReadAllText(deviceIdPath).Trim();
    }

    var deviceId = Guid.NewGuid().ToString();

    var directory = Path.GetDirectoryName(deviceIdPath);
    if (directory != null)
    {
        Directory.CreateDirectory(directory);
        File.WriteAllText(deviceIdPath, deviceId);
    }

    return deviceId;
}