using Wavee.Controls.Lyrics.Helper;
using System.Collections.Generic;
using System.Linq;

namespace Wavee.Controls.Lyrics.Models.Lyrics
{
    public class LyricsData
    {
        public List<LyricsLine> LyricsLines { get; set; } = [];

        private string? _languageCode;
        public string? LanguageCode
        {
            // Lazily runs statistical language detection (NTextCat) on first read
            // and caches the result. Callers on a non-interactive / background path
            // (e.g. caching lyrics during the silent startup auto-resume) should
            // read LanguageCodeOrNull instead, so they don't pay the ~MB profile
            // load + parse before the value is actually needed for display.
            get => _languageCode ??= LanguageHelper.DetectLanguageCode(LyricsLines.Select(line => line.PrimaryText));
            set => _languageCode = value;
        }

        /// <summary>The already-resolved language code, or null if detection hasn't
        /// run yet. Reading this does NOT trigger NTextCat language detection.</summary>
        public string? LanguageCodeOrNull => _languageCode;
        public bool AutoGenerated { get; set; } = false;
        public string WrappedOriginalText => string.Join(StringHelper.NewLine, LyricsLines.Select(line => line.PrimaryText));
        public bool IsWordByWord => LyricsLines.Any(x => x.IsPrimaryHasRealSyllableInfo);

        public LyricsData()
        {
        }

        public LyricsData(List<LyricsLine> lyricsLines)
        {
            LyricsLines = lyricsLines;
        }

    }
}